# Generated by Django 2.1.3 on 2019-07-06 09:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0002_auto_20190706_1348'),
    ]

    operations = [
        migrations.CreateModel(
            name='Label',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('location', models.CharField(default='', max_length=244)),
                ('label', models.IntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name='savetransactions',
            name='merchant',
        ),
        migrations.RemoveField(
            model_name='savetransactions',
            name='user',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='account_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='bank_name',
        ),
        migrations.DeleteModel(
            name='Merchant',
        ),
        migrations.DeleteModel(
            name='SaveTransactions',
        ),
        migrations.AddField(
            model_name='label',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stp.CustomUser'),
        ),
    ]
