# Generated by Django 2.1.3 on 2019-07-06 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stp', '0003_auto_20190706_1743'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ally',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=255)),
                ('contact_number', models.CharField(default='', max_length=20)),
            ],
        ),
        migrations.AddField(
            model_name='customuser',
            name='registered_as_ally',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ally',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='stp.CustomUser'),
        ),
    ]
